# Generated by Django 4.0.4 on 2022-04-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=250, verbose_name='Keywords')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Категория продукты',
                'verbose_name_plural': 'Категории продукты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=250, verbose_name='Keywords')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='img_product')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=70, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productcategory')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
